# fly.toml file generated for zui-botto on 2023-03-28T08:02:01+08:00

app = "zui-botto"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
